name: Release

on:
  push:
    paths:
      - 'version.py'
      - '.github/workflows/release.yml'
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g. v1.2.3). If provided, a release will be created/updated.'
        required: false
        default: ''
      create_tag:
        description: 'Create tag from version.py and publish'
        required: false
        default: 'false'

permissions:
  contents: write

jobs:
  build:
    name: Build (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-13]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Read version from version.py or tag
        id: version
        env:
          TAG_INPUT: ${{ github.event.inputs.tag }}
        run: |
          python - << 'PY'
          import os, re, sys
          tag_input = os.environ.get('TAG_INPUT', '')
          ref = os.environ.get('GITHUB_REF', '')
          ref_name = os.environ.get('GITHUB_REF_NAME', '')
          tag = ref_name if ref.startswith('refs/tags/') else (tag_input or '')
          if tag:
              ver = tag.lstrip('vV')
          else:
              import version as _v
              ver = _v.__version__
          # 语义化版本校验
          if not re.match(r'^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-[0-9A-Za-z.-]+)?$', ver):
              print(f'Invalid semantic version: {ver}', file=sys.stderr)
              sys.exit(1)
          with open(os.environ['GITHUB_OUTPUT'], 'a', encoding='utf-8') as out:
              out.write(f'version={ver}\n')
          PY

      - name: Build executable
        run: |
          python build_app.py

      - name: Rename and zip artifact (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        env:
          APP_VERSION: ${{ steps.version.outputs.version }}
        run: |
          $arch = "$env:RUNNER_ARCH"
          $exe = "dist/TomatoNovelDownloader.exe"
          if (!(Test-Path $exe)) { throw "Not found: $exe" }
          $new = "dist/TomatoNovelDownloader_v$env:APP_VERSION`_windows_$arch.exe"
          Move-Item $exe $new -Force
          $zip = [System.IO.Path]::ChangeExtension($new, ".zip")
          if (Test-Path $zip) { Remove-Item $zip -Force }
          Compress-Archive -Path $new -DestinationPath $zip -Force

      - name: Rename and zip artifact (*nix)
        if: runner.os != 'Windows'
        shell: bash
        env:
          APP_VERSION: ${{ steps.version.outputs.version }}
        run: |
          set -euo pipefail
          arch="${RUNNER_ARCH}"
          plat=$(echo "${RUNNER_OS}" | tr '[:upper:]' '[:lower:]')
          if [ -d "dist/TomatoNovelDownloader.app" ]; then
            name="dist/TomatoNovelDownloader_v${APP_VERSION}_${plat}_${arch}.app"
            mv "dist/TomatoNovelDownloader.app" "$name"
            zip -r -9 "${name%.app}.zip" "$(basename "$name")" -x "*.DS_Store" -x "__MACOSX"
          elif [ -f "dist/TomatoNovelDownloader" ]; then
            name="dist/TomatoNovelDownloader_v${APP_VERSION}_${plat}_${arch}"
            mv "dist/TomatoNovelDownloader" "$name"
            zip -9 -j "${name}.zip" "$name"
          else
            echo "No expected build output found in dist/" >&2
            ls -la dist/ || true
            exit 1
          fi

      - name: Upload artifact (per-OS)
        uses: actions/upload-artifact@v4
        with:
          name: TomatoNovelDownloader-${{ matrix.os }}

      - name: Create tag from version.py (optional)
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.create_tag == 'true' }}
        env:
          V: ${{ steps.version.outputs.version }}
        run: |
          set -euo pipefail
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git fetch --tags --depth=1
          if git rev-parse -q --verify "refs/tags/v$V" >/dev/null; then
            echo "Tag v$V already exists"
          else
            git tag -a "v$V" -m "Release v$V"
            git push origin "v$V"
          fi



  publish:
    name: Publish Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Compute version
        id: version
        env:
          TAG_INPUT: ${{ github.event.inputs.tag }}
        run: |
          python - << 'PY'
          import os
          ref = os.environ.get('GITHUB_REF','')
          ref_name = os.environ.get('GITHUB_REF_NAME','')
          tag = ref_name if ref.startswith('refs/tags/') else os.environ.get('TAG_INPUT','')
          ver = tag.lstrip('vV') if tag else ''
          if not ver:
              import version as _v
              ver = _v.__version__
          with open(os.environ['GITHUB_OUTPUT'], 'a', encoding='utf-8') as out:
              out.write(f'version={ver}\n')
          PY

      - name: Ensure tag exists
        env:
          V: ${{ steps.version.outputs.version }}
        run: |
          set -euo pipefail
          git fetch --tags --depth=1
          if git rev-parse -q --verify "refs/tags/v$V" >/dev/null; then
            echo "Tag v$V already exists"
          else
            git config user.name "github-actions"
            git config user.email "github-actions@users.noreply.github.com"
            git tag -a "v$V" -m "Release v$V"
            git push origin "v$V"
          fi

      - name: Build release metadata
        id: meta
        run: |
          short="${GITHUB_SHA::7}"
          tz="Asia/Shanghai"
          build_time=$(TZ=$tz date '+%Y-%m-%d %H:%M:%S (%Z)')
          echo "short_sha=$short" >> "$GITHUB_OUTPUT"
          echo "build_time=$build_time" >> "$GITHUB_OUTPUT"

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: TomatoNovelDownloader-*
          merge-multiple: true
          path: release_assets

      - name: Create/Update GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/') || (github.event.inputs.tag != '')
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: Tomato Novel Downloader v${{ steps.version.outputs.version }}
          draft: false
          prerelease: false
          body: |
            Version: v${{ steps.version.outputs.version }}
            Build time: ${{ steps.meta.outputs.build_time }}
            Commit: ${{ steps.meta.outputs.short_sha }}
          files: |
            release_assets/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}